import type { NextPage } from "next";
import Head from "next/head";
import { Top } from "./components/templates/Top";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>都道府県別の総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Top />
      </main>
    </div>
  );
};

export default Home;
